# Generated by Django 4.2.2 on 2023-07-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='BLprofile.png', upload_to='profile_images'),
        ),
    ]
