# Generated by Django 4.2.2 on 2023-07-25 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blapp', '0007_post_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
