# Generated by Django 4.2.2 on 2023-07-26 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blapp', '0014_alter_post_user_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
