# Generated by Django 4.2.2 on 2023-07-26 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blapp', '0015_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
