# Generated by Django 4.2.2 on 2023-07-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blapp', '0017_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='BLprofile.pnd', upload_to='profile_images'),
        ),
    ]
