# Generated by Django 4.2.2 on 2023-07-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blapp', '0018_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='BLprofile.png', upload_to='profile_images'),
        ),
    ]
