# Generated by Django 4.2.2 on 2023-07-26 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blapp', '0020_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
