# Generated by Django 4.2.2 on 2023-08-01 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blapp', '0026_followerscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_profile', to='blapp.post')),
                ('uploader_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploader_post_profile', to='blapp.profile')),
            ],
        ),
    ]
