# Generated by Django 4.2.2 on 2023-08-01 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blapp', '0027_postprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostProfile',
        ),
    ]
